### ISSUE TITLE
Add next and previous icon beside month and year

### ISSUE THREAD

**Issue by ishtiaque05** [ishtiaque05/universal-date-picker#1]
![nav-arrow](https://user-images.githubusercontent.com/11247605/47185359-fec47d80-d34e-11e8-8125-64c5b31811f5.png)

The functionality is already implemented. Just improve the UI by adding next and previous icon.

**Comment by n-kovacevic** [comment]
Hi, I can fix this issue if you want.

**Comment by ishtiaque05** [comment]
@nkg5 sure go ahead 😊
